### ISSUE TITLE
Ambient Sound - J#Base.are

### ISSUE THREAD

**Issue by TotoR115** [Pocket-Plane-Group/Lure_Of_Sirines_Call#7]
In J#Base.are, the Ambient sound (offset 0x578) AM_2005 does not exist for oBG2 (with BGT, I don't know for ee or Tutu). It could be replaced by AM_2002 (cave sound)

**Comment by Gitjas** [comment]
Thank you for reporting!
I feel a bit daft but I don't see AM_2002.wav in my install(s), either. Actually, I don't find any sounds that start with "AM_". EDIT: only AM_MRTxx.wav for EET so far.

**Comment by Gitjas** [comment]
Ah, found it, it's an IWD sound. Will be integrated in the next version.

**Comment by Gitjas** [comment]
Fixed in 16.3.
